import {
  Challenge,
  Proposal,
  Prototype,
  TestReport,
  Winner,
  Pilot,
  NotificationItem,
  AuditLogItem,
  StartupProfile,
} from './types';

export const SIMULATION_EXTRA_STARTUPS: StartupProfile[] = [
  {
    id: 'startup-jal',
    userId: 'user-startup-jal',
    name: 'JalVigyan Technologies Pvt Ltd',
    dpiitNumber: 'DIPP-64192',
    dpiitVerified: true,
    panNumber: 'AAACJ9941M',
    gstNumber: '09AAACJ9941M1Z8',
    udyamNumber: 'UDYAM-UP-03-0081290',
    website: 'https://jalvigyan.in',
    description: 'Autonomous solar-powered water sentinel buoys and optical pollutant dispersion telemetry for national river basins.',
    foundingYear: 2021,
    teamSize: 18,
    sectors: ['Water & Environment', 'IoT & DeepTech', 'CleanTech'],
    technologies: ['Spectrophotometry', 'Solar IoT', 'NB-IoT', 'Hydrodynamic Drift AI'],
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    pincode: '208016',
    bankAccountNumber: '38190201004123',
    ifscCode: 'SBIN0001144',
    accountHolderName: 'JalVigyan Technologies Private Limited',
  },
  {
    id: 'startup-krishi',
    userId: 'user-startup-krishi',
    name: 'KrishiDrishti AgriSensors',
    dpiitNumber: 'DIPP-77821',
    dpiitVerified: true,
    panNumber: 'AABCK4821E',
    gstNumber: '29AABCK4821E1ZQ',
    udyamNumber: 'UDYAM-KA-03-0044192',
    website: 'https://krishidrishti.farm',
    description: 'Hyper-local soil nutrient spectroscopy and satellite-fused pest outbreak early warning system for smallholder farmers.',
    foundingYear: 2020,
    teamSize: 22,
    sectors: ['Agriculture & Allied', 'AI & Remote Sensing', 'Rural Tech'],
    technologies: ['Hyperspectral Imaging', 'ISRO Bhuvan GIS', 'Edge ML', 'LoRaWAN'],
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560064',
    bankAccountNumber: '04210020109823',
    ifscCode: 'ICIC0000421',
    accountHolderName: 'KrishiDrishti AgriSensors India Private Limited',
  },
  {
    id: 'startup-raksha',
    userId: 'user-startup-raksha',
    name: 'RakshaAvionics Defense Labs',
    dpiitNumber: 'DIPP-93210',
    dpiitVerified: true,
    panNumber: 'AABCR8102J',
    gstNumber: '06AABCR8102J1ZX',
    udyamNumber: 'UDYAM-HR-04-0019283',
    website: 'https://rakshaavionics.in',
    description: 'Swarm drone border surveillance with jam-resistant NavIC satellite telemetry and thermal object tracking.',
    foundingYear: 2022,
    teamSize: 35,
    sectors: ['Defense & Aerospace', 'Robotics & Drones', 'AI'],
    technologies: ['NavIC Differential GPS', 'Thermal FLIR Edge AI', 'Anti-Jamming RF', 'Carbon Fiber Airframes'],
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122018',
    bankAccountNumber: '91202008471920',
    ifscCode: 'UTIB0000847',
    accountHolderName: 'RakshaAvionics Defense Systems Private Limited',
  },
];

export const SIMULATION_EXTRA_CHALLENGES: Challenge[] = [
  {
    id: 'ch-drdo-06',
    governmentDeptId: 'govt-drdo',
    ministryName: 'Ministry of Defence',
    departmentName: 'Defence Research and Development Organisation (DRDO)',
    contactPerson: 'Brig. Vikramjit Singh, Director (Technology Development Fund)',
    title: 'Autonomous High-Altitude Heavy-Payload Logistics UAV for Snowbound Posts',
    slug: 'autonomous-high-altitude-payload-logistics-uav-drdo',
    problemStatement: 'Forward border outposts at altitudes exceeding 14,000 feet experience severe winter road isolation. Border forces require autonomous VTOL (Vertical Take-off and Landing) cargo drones capable of lifting 35 kg of emergency supplies, ammunition, or medical kits in sub-zero winds without GPS dependence.',
    expectedOutcomes: '1. Service ceiling minimum 16,000 feet above sea level.\n2. Autonomous return-to-home under NavIC jamming conditions.\n3. Turnaround time under 20 minutes with hot-swappable battery modules.\n4. Low thermal and acoustic radar signature.',
    sector: 'Defence & Security',
    tags: ['DRDO', 'High Altitude', 'UAV Logistics', 'Make in India', 'Defense Tech'],
    budgetMin: 6000000,
    budgetMax: 10000000,
    currency: 'INR',
    timelineMonths: 9,
    eligibilityCriteria: 'DPIIT recognized startup with indigenous defense manufacturing and DIPP clearance.',
    evaluationCriteria: 'High altitude aerodynamics, payload stability under 40-knot crosswinds, electronic warfare resilience.',
    status: 'APPLICATION_OPEN',
    applicationDeadline: '2026-11-15T18:00:00Z',
    publishedAt: '2026-08-25T10:00:00Z',
    totalApplications: 4,
    shortlistedCount: 1,
    winnerCount: 0,
    pilotLocation: 'Leh-Ladakh Sector & Siachen Base Camp (12,000 to 15,500 ft ASL)',
  },
  {
    id: 'ch-agri-07',
    governmentDeptId: 'govt-agri',
    ministryName: 'Ministry of Agriculture & Farmers Welfare',
    departmentName: 'Department of Agriculture & Cooperation (DAC&FW)',
    contactPerson: 'Dr. Meenakshi Sunder, Joint Secretary (Crops & Digital Ag)',
    title: 'Multi-Spectral Satellite & Ground Sensor Fusion for Early Fall Armyworm Prediction',
    slug: 'multispectral-satellite-sensor-fusion-pest-prediction',
    problemStatement: 'Invasive pests like Fall Armyworm (Spodoptera frugiperda) cause up to ₹3,000 Crores in crop loss annually across maize and cotton belts. Farmers need an automated early-warning tool that correlates ISRO satellite NDVI vegetative anomalies with soil moisture micro-climate telemetry to alert village Panchayats 7 days prior to infestation.',
    expectedOutcomes: '1. Early prediction accuracy >88% across 10,000 target hectares.\n2. SMS / WhatsApp advisory in Hindi, Kannada, and Marathi to registered Kisan cards.\n3. Integrated biological pest control recommendation reducing chemical pesticide expenditure by 40%.',
    sector: 'Agriculture & Rural Development',
    tags: ['AgriTech', 'ISRO Bhuvan', 'Pest Outbreak', 'Kisan Samridhi', 'AI for Agriculture'],
    budgetMin: 3000000,
    budgetMax: 5500000,
    currency: 'INR',
    timelineMonths: 6,
    eligibilityCriteria: 'DPIIT startup with agricultural data science and remote sensing expertise.',
    evaluationCriteria: 'Predictive algorithm reliability, field validation data, vernacular accessibility for farmers.',
    status: 'EVALUATION_IN_PROGRESS',
    applicationDeadline: '2026-09-01T18:00:00Z',
    publishedAt: '2026-07-25T10:00:00Z',
    totalApplications: 7,
    shortlistedCount: 2,
    winnerCount: 0,
    pilotLocation: 'Dharwad & Haveri Districts (Karnataka) - 50 Village Panchayats',
  },
];

export const SIMULATION_EXTRA_PROPOSALS: Proposal[] = [
  {
    id: 'prop-jal-1',
    challengeId: 'ch-jal-04',
    challengeTitle: 'Autonomous Solar Water Quality Sentinel Buoys with Pollutant Source Tracing',
    startupId: 'startup-jal',
    startupName: 'JalVigyan Technologies Pvt Ltd',
    dpiitNumber: 'DIPP-64192',
    title: 'GangaSentinel: Solar-Powered Autonomous Multi-Spectral Water Quality Buoy Network',
    slug: 'gangasentinel-solar-water-buoy-network',
    solutionOverview: 'GangaSentinel is an autonomous catamaran buoy equipped with submerged optical fluorometers, ion-selective electrodes, and a GPS-linked telemetry node. It measures pH, Dissolved Oxygen (DO), Turbidity, BOD, COD, and ammoniacal nitrogen every 15 minutes, transmitting alerts to NMCG and CPCB servers via 4G/NB-IoT.',
    technicalApproach: '1. Self-cleaning wiper mechanism driven by ultra-low power brushless servo preventing algae fouling.\n2. In-situ spectrophotometry calibrated against Central Water Commission (CWC) laboratory standards.\n3. Hydrodynamic drift modeling engine running on cloud GIS predicting effluent plume trajectories.',
    innovation: 'Proprietary anti-biofouling ultrasonic transducer array that extends unattended river deployment from 14 days to 180 continuous days without manual cleaning.',
    teamDetails: 'Founded by Dr. Alok Tripathi (PhD Environmental Engineering, IIT Kanpur) with 18 engineers and aquatic instrumentation technicians.',
    budgetBreakdown: {
      rdDevelopment: 1100000,
      hardwareInfrastructure: 1500000,
      pilotTesting: 600000,
      teamManpower: 700000,
      contingency: 150000,
    },
    totalBudget: 4050000,
    timelineMonths: 6,
    impactMetrics: 'Deployed across 85 km Ganga stretch between Kanpur and Prayagraj; monitors 24 industrial drains with 99.2% uptime.',
    scalability: 'Modular manufacturing allows assembly of 50 buoys per month at Kanpur facility.',
    riskAnalysis: 'Risk: High monsoon river velocity (up to 3.5 m/s). Mitigation: High-tensile stainless steel mooring tether with hydrodynamic low-drag hull design.',
    documents: [
      { name: 'GangaSentinel_Tech_Spec_v3.pdf', size: '5.1 MB', url: '#' },
      { name: 'NABL_Calibration_Certificate.pdf', size: '2.4 MB', url: '#' },
    ],
    status: 'SHORTLISTED',
    aiScore: 93.8,
    aiScoreBreakdown: {
      problemSolutionFit: 98,
      technicalFeasibility: 94,
      innovation: 95,
      impactPotential: 96,
      teamCapability: 93,
      scalability: 91,
      riskManagement: 89,
      costEffectiveness: 88,
      overall: 93.8,
    },
    aiExplanation: 'Exemplary alignment with National Mission for Clean Ganga mandates. Technical feasibility is validated by IIT Kanpur incubation benchmarks. The ultrasonic anti-biofouling innovation solves a major pain point in aquatic sensor networks. Ranked G1 Leader.',
    g1Category: true,
    g2Category: false,
    rankG1: 1,
    submittedAt: '2026-08-20T12:00:00Z',
    prototypeSubmitted: true,
  },
  {
    id: 'prop-drdo-1',
    challengeId: 'ch-drdo-06',
    challengeTitle: 'Autonomous High-Altitude Heavy-Payload Logistics UAV for Snowbound Posts',
    startupId: 'startup-raksha',
    startupName: 'RakshaAvionics Defense Labs',
    dpiitNumber: 'DIPP-93210',
    title: 'HimGaruda-V35: Hybrid VTOL Heavy-Lift Logistics Drone with NavIC Resilient Flight Controller',
    slug: 'himgaruda-hybrid-vtol-defense-uav',
    solutionOverview: 'HimGaruda is a carbon-composite hybrid VTOL UAV combining quadcopter vertical takeoff with fixed-wing forward cruise efficiency. Powered by cold-tolerant solid-state batteries with internal heating elements, it lifts 35 kg payloads to altitudes of 16,500 feet in -25°C conditions.',
    technicalApproach: 'Indigenously designed flight controller with differential NavIC/GPS fusion, optical terrain flow odometer for GPS-denied navigation, and encrypted MIL-STD-1553 bus architecture.',
    innovation: 'Patent-pending active rotor de-icing leading edges and smart thermal battery management sustaining flight duration up to 90 minutes in extreme cold.',
    teamDetails: 'Led by Col. Ramanujam (Retd. Army Aviation Corps) and Dr. Vikram Iyer (Ex-DRDO Aeronautical Development Establishment scientist).',
    budgetBreakdown: {
      rdDevelopment: 2500000,
      hardwareInfrastructure: 3200000,
      pilotTesting: 1400000,
      teamManpower: 1200000,
      contingency: 400000,
    },
    totalBudget: 8700000,
    timelineMonths: 8,
    impactMetrics: 'Reduces emergency medical transport time to remote forward posts from 18 hours (mule track) to 25 minutes; saves critical soldier lives during avalanche isolation.',
    scalability: 'Airframes molded in-house; ready for line production under Make in India Defense Industrial Corridor.',
    riskAnalysis: 'Risk: High wind turbulence in Himalayan mountain passes. Mitigation: Coaxial rotor configuration with gust-rejection control algorithms tested up to 45 knots.',
    documents: [
      { name: 'HimGaruda_DRDO_Proposal_Technical.pdf', size: '7.8 MB', url: '#' },
      { name: 'High_Altitude_Wind_Tunnel_Report.pdf', size: '4.2 MB', url: '#' },
    ],
    status: 'SHORTLISTED',
    aiScore: 94.6,
    aiScoreBreakdown: {
      problemSolutionFit: 97,
      technicalFeasibility: 95,
      innovation: 96,
      impactPotential: 98,
      teamCapability: 96,
      scalability: 89,
      riskManagement: 92,
      costEffectiveness: 84,
      overall: 94.6,
    },
    aiExplanation: 'Top-tier defense technological capability with indigenous flight controller hardware. The hybrid VTOL design and cold-weather thermal envelope directly address DRDO operational requirements in Northern high-altitude sectors. Unanimously rated G1 Leader.',
    g1Category: true,
    g2Category: false,
    rankG1: 1,
    submittedAt: '2026-08-28T09:30:00Z',
    prototypeSubmitted: true,
  },
  {
    id: 'prop-agri-1',
    challengeId: 'ch-agri-07',
    challengeTitle: 'Multi-Spectral Satellite & Ground Sensor Fusion for Early Fall Armyworm Prediction',
    startupId: 'startup-krishi',
    startupName: 'KrishiDrishti AgriSensors',
    dpiitNumber: 'DIPP-77821',
    title: 'KisanSuraksha AI: Edge Pest Sentinel Network with ISRO Bhuvan Geo-Analytics',
    slug: 'kisansuraksha-pest-sentinel-network',
    solutionOverview: 'KisanSuraksha pairs low-cost solar pheromone trap cameras that count and classify adult armyworm moths with ISRO Bhuvan satellite NDVI data to generate micro-watershed pest infestation forecasts 7 to 10 days in advance.',
    technicalApproach: 'Edge computer vision on ESP32-CAM module counting captured insects in real time; sends telemetry via LoRaWAN to village kiosk; cloud GIS model correlates weather, crop age, and spore trajectory.',
    innovation: 'Ultra-low cost solar trap (< ₹2,800/unit) with 10-year lifespan and non-toxic species-specific LED lure frequency.',
    teamDetails: 'Team of agronomists from UAS Dharwad and data scientists from IISc Bengaluru.',
    budgetBreakdown: {
      rdDevelopment: 900000,
      hardwareInfrastructure: 1400000,
      pilotTesting: 600000,
      teamManpower: 800000,
      contingency: 100000,
    },
    totalBudget: 3800000,
    timelineMonths: 6,
    impactMetrics: 'Protects 10,000 hectares across 50 villages; reduces crop yield loss by 72% and cuts toxic chemical pesticide spraying by 45%.',
    scalability: 'Device easily manufactured by rural MSME clusters using injection-molded recycled plastics.',
    riskAnalysis: 'Risk: Weak 4G connectivity in deep agricultural fields. Mitigation: Sub-GHz LoRa mesh network routing alerts to Panchayat common service centers.',
    documents: [
      { name: 'KisanSuraksha_Pilot_Study_2025.pdf', size: '3.9 MB', url: '#' },
      { name: 'Field_Validation_ICAR_Dharwad.pdf', size: '2.1 MB', url: '#' },
    ],
    status: 'SUBMITTED',
    aiScore: 90.5,
    aiScoreBreakdown: {
      problemSolutionFit: 94,
      technicalFeasibility: 91,
      innovation: 89,
      impactPotential: 95,
      teamCapability: 90,
      scalability: 93,
      riskManagement: 86,
      costEffectiveness: 92,
      overall: 90.5,
    },
    aiExplanation: 'Strong rural impact potential with low capital expenditure per village. Demonstrates robust integration with ISRO Bhuvan satellite layers and regional Kisan advisory protocols. Highly recommended for technical committee review.',
    g1Category: true,
    g2Category: false,
    rankG1: 1,
    submittedAt: '2026-09-02T11:00:00Z',
    prototypeSubmitted: false,
  },
];

export const SIMULATION_EXTRA_PROTOTYPES: Prototype[] = [
  {
    id: 'proto-jal-1',
    proposalId: 'prop-jal-1',
    challengeId: 'ch-jal-04',
    startupId: 'startup-jal',
    startupName: 'JalVigyan Technologies Pvt Ltd',
    solutionTitle: 'GangaSentinel: Solar-Powered Autonomous Multi-Spectral Water Quality Buoy Network',
    submissionUrl: 'https://telemetry.jalvigyan.in/cpcb-sandbox',
    demoVideoUrl: 'https://youtube.com/watch?v=mock_gangasentinel_buoy',
    repositoryUrl: 'https://github.com/jalvigyan-tech/gangasentinel-firmware',
    documentation: [
      { title: 'Optical Sensor Calibration Data Sheet', url: '#' },
      { title: 'STQC River Test Protocol Manual', url: '#' },
      { title: 'CPCB REST API Data Schema', url: '#' },
    ],
    architectureNotes: 'Shipped 3 calibrated sentinel buoys to STQC Directorate and National Institute of Hydrology for joint physical endurance trials on Ganga river.',
    submissionDate: '2026-08-25T14:00:00Z',
    status: 'TEST_PASSED',
    testReportId: 'rep-stqc-jal-01',
  },
  {
    id: 'proto-drdo-1',
    proposalId: 'prop-drdo-1',
    challengeId: 'ch-drdo-06',
    startupId: 'startup-raksha',
    startupName: 'RakshaAvionics Defense Labs',
    solutionTitle: 'HimGaruda-V35: Hybrid VTOL Heavy-Lift Logistics Drone',
    submissionUrl: 'https://avionics.rakshadefense.in/telemetry-sim',
    demoVideoUrl: 'https://youtube.com/watch?v=mock_himgaruda_ladakh',
    repositoryUrl: 'https://github.com/raksha-avionics/himgaruda-vtol-flight-control',
    documentation: [
      { title: 'Flight Test Telemetry Logs (14,500 ft ASL)', url: '#' },
      { title: 'Payload Release Mechanism Safety Certification', url: '#' },
    ],
    architectureNotes: 'Delivered 1 flight unit with cold-soak test data to Army Airborne Trials Wing and DRDO ADE for field testing.',
    submissionDate: '2026-08-30T16:00:00Z',
    status: 'UNDER_TESTING',
    testReportId: 'rep-arai-drdo-01',
  },
];

export const SIMULATION_EXTRA_TEST_REPORTS: TestReport[] = [
  {
    id: 'rep-stqc-jal-01',
    prototypeId: 'proto-jal-1',
    proposalId: 'prop-jal-1',
    challengeId: 'ch-jal-04',
    startupName: 'JalVigyan Technologies Pvt Ltd',
    solutionTitle: 'GangaSentinel: Solar-Powered Autonomous Multi-Spectral Water Quality Buoy Network',
    testingOrgId: 'org-stqc',
    testingOrgName: 'STQC Directorate (Standardisation Testing and Quality Certification), MeitY',
    functionalityScore: 10,
    performanceScore: 9,
    securityScore: 10,
    usabilityScore: 9,
    integrationScore: 9,
    overallScore: 94,
    functionalityReport: 'Chemical spectrophotometry sensors were immersed in calibrated standard solutions of BOD, COD, and ammoniacal nitrogen across 14 consecutive days. Measurement deviation remained strictly under 3.1% compared to laboratory gas chromatography benchmarks.',
    performanceReport: 'Solar charging circuit maintained 94% battery capacity even during 48-hour continuous overcast cloud simulation. Cellular telemetry latency was under 850 ms.',
    securityReport: 'Hardware encryption chip (ATECC608A) validated for secure MQTT authentication. Telemetry stream is tamper-proof against MITM attacks.',
    usabilityReport: 'Deployable by 2 field operators from a standard river boat without specialized crane rigging.',
    integrationReport: 'Successfully streams continuous JSON telemetry into CPCB National Water Quality Dashboard gateway.',
    issues: [
      'Mooring shackle pin should use grade 316L marine stainless steel to prevent long-term river silt corrosion.',
    ],
    recommendations: 'Recommended for unconditional approval and pilot sanction by Ministry of Jal Shakti. Prototype sets an outstanding national benchmark for aquatic environmental sensing.',
    verdict: 'PASS',
    certificateNumber: 'STQC/DEL/2026/WATER-9941',
    submittedAt: '2026-08-31T15:30:00Z',
  },
];

export const SIMULATION_EXTRA_PILOTS: Pilot[] = [
  {
    id: 'pilot-jal-2',
    challengeId: 'ch-jal-04',
    challengeTitle: 'Autonomous Solar Water Quality Sentinel Buoys with Pollutant Source Tracing',
    winnerId: 'win-jal-1',
    startupId: 'startup-jal',
    startupName: 'JalVigyan Technologies Pvt Ltd',
    location: 'Ganga River Basin - Kanpur Jajmau Industrial Tannery Stretch (35 km)',
    startDate: '2026-09-01T00:00:00Z',
    endDate: '2027-02-28T00:00:00Z',
    status: 'IN_PROGRESS',
    totalBudget: 4050000,
    totalSanctionedAmount: 4050000,
    disbursedAmount: 1620000,
    progress: 45,
    currentPhase: 'Phase 2: Continuous Real-Time Telemetry & CPCB Alert Integration',
    milestones: [
      {
        id: 'ms-jal-1',
        title: 'Buoy Fabrication & Hydrodynamic Balancing Calibration',
        description: 'Manufacture 6 catamaran buoys with dual solar arrays and ultrasonic wipers. Conduct static pool buoyancy tests.',
        paymentPercentage: 40,
        paymentAmount: 1620000,
        dueDate: '2026-09-15T00:00:00Z',
        status: 'COMPLETED',
        paymentStatus: 'PAID',
        deliverablesUrl: 'https://jalvigyan.in/milestones/ms1-report.pdf',
        paidAt: '2026-09-02T16:00:00Z',
        utrNumber: 'RBI-NEFT-2026-JAL-00192',
      },
      {
        id: 'ms-jal-2',
        title: 'River Deployment & CPCB Cloud API Stream Activation',
        description: 'Deploy 6 buoys at key drain outfalls along Kanpur leather industrial clusters. Achieve 98% uninterrupted data stream for 30 consecutive days.',
        paymentPercentage: 35,
        paymentAmount: 1417500,
        dueDate: '2026-10-31T00:00:00Z',
        status: 'IN_PROGRESS',
        paymentStatus: 'REQUESTED',
        deliverablesUrl: 'https://jalvigyan.in/milestones/ms2-cpcb-live-data.pdf',
      },
      {
        id: 'ms-jal-3',
        title: 'Monsoon Resilience Evaluation & Final Handover to NMCG',
        description: 'Comprehensive 90-day water quality trend report and integration with National Hydrology Project database.',
        paymentPercentage: 25,
        paymentAmount: 1012500,
        dueDate: '2027-02-28T00:00:00Z',
        status: 'PENDING',
        paymentStatus: 'PENDING',
      },
    ],
  },
  {
    id: 'pilot-mohfw-3',
    challengeId: 'ch-mohfw-02',
    challengeTitle: 'Offline-First AI Clinical Triage & Tele-Diagnostics for Sub-Centers',
    winnerId: 'win-mohfw-1',
    startupId: 'startup-2',
    startupName: 'SwasthyaSetu HealthTech',
    location: 'Gadchiroli District (Maharashtra) - 24 Tribal Primary Health Sub-Centers',
    startDate: '2026-09-01T00:00:00Z',
    endDate: '2027-05-31T00:00:00Z',
    status: 'IN_PROGRESS',
    totalBudget: 5000000,
    totalSanctionedAmount: 5000000,
    disbursedAmount: 2000000,
    progress: 35,
    currentPhase: 'Phase 1: ASHA Frontline Worker Training & Tablet Kit Handover',
    milestones: [
      {
        id: 'ms-mohfw-1',
        title: '24 Diagnostic Tablet Kits Delivered & ASHA Certification',
        description: 'Procure and provision 24 ruggedized medical diagnostic kits with Bluetooth 12-lead ECG, dermascope, and multi-lingual voice assistant.',
        paymentPercentage: 40,
        paymentAmount: 2000000,
        dueDate: '2026-09-30T00:00:00Z',
        status: 'COMPLETED',
        paymentStatus: 'PAID',
        deliverablesUrl: 'https://swasthyasetu.health/reports/gadchiroli-phase1.pdf',
        paidAt: '2026-09-03T11:20:00Z',
        utrNumber: 'RBI-NEFT-2026-HLTH-88219',
      },
      {
        id: 'ms-mohfw-2',
        title: '5,000 Tribal Patient Screenings with ABHA Push',
        description: 'Complete 5,000 clinical triages with ABDM M3 health record generation and tele-consultations with district hospital physicians.',
        paymentPercentage: 35,
        paymentAmount: 1750000,
        dueDate: '2026-12-31T00:00:00Z',
        status: 'IN_PROGRESS',
        paymentStatus: 'PENDING',
      },
      {
        id: 'ms-mohfw-3',
        title: 'Impact Evaluation & GeM Scaling Transition',
        description: 'State Directorate of Health Services clinical audit and formal technical validation for state-wide GeM procurement expansion.',
        paymentPercentage: 25,
        paymentAmount: 1250000,
        dueDate: '2027-05-31T00:00:00Z',
        status: 'PENDING',
        paymentStatus: 'PENDING',
      },
    ],
  },
];

export const SIMULATION_EXTRA_WINNERS: Winner[] = [
  {
    id: 'win-jal-1',
    challengeId: 'ch-jal-04',
    proposalId: 'prop-jal-1',
    startupId: 'startup-jal',
    startupName: 'JalVigyan Technologies Pvt Ltd',
    solutionTitle: 'GangaSentinel: Solar-Powered Autonomous Water Quality Buoy Network',
    rank: 1,
    prizeAmount: 4050000,
    selectedAt: '2026-08-31T18:00:00Z',
    notes: 'Awarded by the National Mission for Clean Ganga Technical Committee based on top G1 AI score (93.8/100) and STQC laboratory test pass certificate (94/100).',
    contractNumber: 'NMCG/TECH/2026/SANGAM-002',
  },
  {
    id: 'win-mohfw-1',
    challengeId: 'ch-mohfw-02',
    proposalId: 'prop-mohfw-1',
    startupId: 'startup-2',
    startupName: 'SwasthyaSetu HealthTech',
    solutionTitle: 'ArogyaDrishti: Multi-modal Offline Diagnostic AI Kit',
    rank: 1,
    prizeAmount: 5000000,
    selectedAt: '2026-08-28T16:00:00Z',
    notes: 'Approved by National Health Authority under GFR 2017 Rule 194 for remote tribal public health deployment.',
    contractNumber: 'NHA/TELEMED/2026/SANGAM-003',
  },
];

export const SIMULATION_EXTRA_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-sim-1',
    userId: 'user-govt-1',
    title: 'STQC Test Certificate Issued (JalVigyan Technologies)',
    message: 'STQC Directorate has uploaded Certificate STQC/DEL/2026/WATER-9941 with overall benchmark score 94/100 (Verdict: PASS).',
    type: 'LAB_REPORT',
    read: false,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'notif-sim-2',
    userId: 'user-startup-1',
    title: 'PFMS Milestone Payment Disbursed: ₹16.20 Lakhs',
    message: 'National Mission for Clean Ganga has released Phase 1 funds via RBI-NEFT. UTR: RBI-NEFT-2026-JAL-00192.',
    type: 'PAYMENT_RECEIVED',
    read: false,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'notif-sim-3',
    userId: 'user-admin-1',
    title: 'New High-Altitude Defence Challenge Live',
    message: 'DRDO Technology Development Fund published: Autonomous High-Altitude Heavy-Payload Logistics UAV.',
    type: 'INFO',
    read: false,
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'notif-sim-4',
    userId: 'user-test-1',
    title: 'Prototype Ready for Lab Benchmarking (HimGaruda VTOL)',
    message: 'RakshaAvionics has submitted 1 hybrid VTOL UAV flight test unit for MeitY / STQC hardware evaluation.',
    type: 'INFO',
    read: false,
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
];

export const SIMULATION_EXTRA_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'log-sim-1',
    userId: 'user-test-1',
    userName: 'Shri K. S. Sundaram (STQC Director)',
    action: 'TEST_REPORT_SUBMITTED',
    entity: 'TestReport',
    entityId: 'rep-stqc-jal-01',
    timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
    ipAddress: '10.14.88.12 (STQC MeitY Secure Network)',
  },
  {
    id: 'log-sim-2',
    userId: 'user-govt-1',
    userName: 'Dr. Rajesh Verma, IAS',
    action: 'PILOT_SANCTIONED',
    entity: 'Pilot',
    entityId: 'pilot-jal-2',
    timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
    ipAddress: '10.14.22.9 (NIC Govt Portal)',
  },
  {
    id: 'log-sim-3',
    userId: 'user-govt-1',
    userName: 'Dr. Rajesh Verma, IAS',
    action: 'PAYMENT_RELEASED',
    entity: 'Milestone',
    entityId: 'ms-jal-1',
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
    ipAddress: '10.14.22.9 (NIC Govt Portal)',
  },
  {
    id: 'log-sim-4',
    userId: 'user-startup-jal',
    userName: 'Dr. Alok Tripathi (JalVigyan Tech)',
    action: 'PROPOSAL_SUBMITTED',
    entity: 'Proposal',
    entityId: 'prop-jal-1',
    timestamp: new Date(Date.now() - 3600000 * 24).toISOString(),
    ipAddress: '117.240.18.91 (DPIIT Startup Gateway)',
  },
];
