import {
  Challenge,
  Proposal,
  Prototype,
  TestReport,
  Winner,
  Pilot,
  StartupProfile,
  GovernmentProfile,
  TestingOrgProfile,
  NotificationItem,
  AuditLogItem,
  User,
  UserRole,
} from './types';
import { evaluateProposalAI, rankAndCategorizeProposals } from './ai-scoring';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-startup-1',
    name: 'Aarav Sharma',
    email: 'aarav@margvision.ai',
    role: 'STARTUP',
    organization: 'MargVision AI Solutions Pvt Ltd',
    phone: '+91 98187 74144',
  },
  {
    id: 'user-govt-1',
    name: 'Dr. Rajesh Verma, IAS',
    email: 'r.verma@morth.gov.in',
    role: 'GOVERNMENT',
    organization: 'Ministry of Road Transport & Highways',
    phone: '+91 11 2371 4500',
  },
  {
    id: 'user-test-1',
    name: 'Shri K. S. Sundaram',
    email: 'director@stqc.gov.in',
    role: 'TESTING_ORG',
    organization: 'STQC Directorate (MeitY)',
    phone: '+91 11 2436 0000',
  },
  {
    id: 'user-admin-1',
    name: 'DPIIT Mission Director',
    email: 'director-dpiit@nic.in',
    role: 'ADMIN',
    organization: 'Department for Promotion of Industry & Internal Trade',
    phone: '+91 11 2306 1234',
  },
];

export const INITIAL_STARTUPS: StartupProfile[] = [
  {
    id: 'startup-1',
    userId: 'user-startup-1',
    name: 'MargVision AI Pvt Ltd',
    dpiitNumber: 'DIPP-89421',
    dpiitVerified: true,
    panNumber: 'AABCM1234F',
    gstNumber: '07AABCM1234F1Z5',
    udyamNumber: 'UDYAM-DL-01-0023451',
    website: 'https://margvision.ai',
    description: 'Edge AI computer vision platform for automated road asset mapping, pothole localization, and traffic safety analytics.',
    foundingYear: 2022,
    teamSize: 24,
    sectors: ['AI & Robotics', 'Mobility & Smart Cities', 'Infrastructure'],
    technologies: ['Computer Vision', 'Edge Computing', 'YOLOv9', 'Geospatial GIS', 'LiDAR'],
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110025',
    bankAccountNumber: '912010048912341',
    ifscCode: 'SBIN0001234',
    accountHolderName: 'MargVision AI Solutions Private Limited',
  },
  {
    id: 'startup-2',
    userId: 'user-startup-2',
    name: 'SwasthyaSetu HealthTech',
    dpiitNumber: 'DIPP-72109',
    dpiitVerified: true,
    panNumber: 'AAECS5678K',
    gstNumber: '27AAECS5678K1Z2',
    udyamNumber: 'UDYAM-MH-02-0098712',
    website: 'https://swasthyasetu.health',
    description: 'AI-assisted point-of-care tele-diagnostics and multi-lingual triage for Primary Health Centers in rural and tribal districts.',
    foundingYear: 2021,
    teamSize: 32,
    sectors: ['Healthcare', 'AI & DeepTech', 'Social Impact'],
    technologies: ['Computer Vision', 'Biomedical Signal Processing', 'Offline-First Sync', 'FHIR/ABDM'],
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411004',
    bankAccountNumber: '502000287162534',
    ifscCode: 'HDFC0000240',
    accountHolderName: 'SwasthyaSetu Health Technologies Pvt Ltd',
  },
  {
    id: 'startup-3',
    userId: 'user-startup-3',
    name: 'AgriDrishti Aerial Systems',
    dpiitNumber: 'DIPP-65432',
    dpiitVerified: true,
    panNumber: 'AALCA8765M',
    gstNumber: '29AALCA8765M1Z8',
    udyamNumber: 'UDYAM-KR-03-0045612',
    website: 'https://agridrishti.in',
    description: 'Hyperspectral drone imaging with automated pest infestation and crop health mapping for PMFBY insurance claims.',
    foundingYear: 2020,
    teamSize: 18,
    sectors: ['Agriculture', 'Drones', 'ClimateTech'],
    technologies: ['Multispectral Imaging', 'Drone Telemetry', 'Crop Yield Models', 'GIS'],
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560038',
    bankAccountNumber: '623401567890',
    ifscCode: 'ICIC0000002',
    accountHolderName: 'AgriDrishti Aerial Systems India Pvt Ltd',
  },
  {
    id: 'startup-4',
    userId: 'user-startup-4',
    name: 'UrjaSense Smart Grid AI',
    dpiitNumber: 'DIPP-91044',
    dpiitVerified: true,
    panNumber: 'AAGCU9012P',
    gstNumber: '24AAGCU9012P1ZA',
    udyamNumber: 'UDYAM-GJ-04-0012399',
    website: 'https://urjasense.io',
    description: 'Non-intrusive IoT sensors and AI algorithms for aggregate technical & commercial (AT&C) power theft and distribution loss localization.',
    foundingYear: 2023,
    teamSize: 15,
    sectors: ['Energy & CleanTech', 'IoT & Smart Grid', 'Utilities'],
    technologies: ['Edge Micro-sensors', 'Current Waveform ML', 'LoRaWAN', 'Cloud Analytics'],
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380015',
    bankAccountNumber: '109823456789',
    ifscCode: 'BARB0AHMEDA',
    accountHolderName: 'UrjaSense Technologies Pvt Ltd',
  },
  {
    id: 'startup-5',
    userId: 'user-startup-5',
    name: 'JalSuraksha Water IoT',
    dpiitNumber: 'DIPP-81290',
    dpiitVerified: true,
    panNumber: 'AAECJ4321R',
    gstNumber: '09AAECJ4321R1Z1',
    udyamNumber: 'UDYAM-UP-05-0078123',
    website: 'https://jalsuraksha.org',
    description: 'Solar-powered multiparameter IoT water quality buoys with real-time pollution source backtracking for Namami Gange.',
    foundingYear: 2022,
    teamSize: 20,
    sectors: ['Water & Sanitation', 'IoT & Environment', 'CleanTech'],
    technologies: ['Optical Spectroscopy', 'Solar Harvesting', 'Satellite Telemetry', 'Pollution Flow Models'],
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    pincode: '208016',
    bankAccountNumber: '398712345678',
    ifscCode: 'PUNB0123400',
    accountHolderName: 'JalSuraksha Innovations Pvt Ltd',
  },
  {
    id: 'startup-6',
    userId: 'user-startup-6',
    name: 'RailPulse Safety Analytics',
    dpiitNumber: 'DIPP-78219',
    dpiitVerified: true,
    panNumber: 'AABCR6543N',
    gstNumber: '19AABCR6543N1Z3',
    udyamNumber: 'UDYAM-WB-06-0043120',
    website: 'https://railpulse.in',
    description: 'Acoustic track vibration sensors and computer vision for predictive railway track defect identification & derailment prevention.',
    foundingYear: 2021,
    teamSize: 26,
    sectors: ['Railways & Transportation', 'DeepTech', 'IoT'],
    technologies: ['Acoustic Emission', 'Optical Gauge Measuring', 'Edge AI', 'Kavach Interface'],
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700091',
    bankAccountNumber: '456789123012',
    ifscCode: 'KKBK0000123',
    accountHolderName: 'RailPulse Safety Systems Private Limited',
  },
];

export const INITIAL_CHALLENGES: Challenge[] = [
  {
    id: 'ch-morth-01',
    governmentDeptId: 'govt-morth',
    ministryName: 'Ministry of Road Transport & Highways',
    departmentName: 'National Highways Authority of India (NHAI)',
    contactPerson: 'Dr. Rajesh Verma, IAS, Chief Engineer (Innovation)',
    title: 'AI-Powered Automated Pothole & Road Quality Survey on National Highways',
    slug: 'ai-powered-automated-pothole-road-survey-nhai',
    problemStatement: 'NHAI currently relies on periodic manual surveys and high-cost Network Survey Vehicles (NSV) which cannot provide real-time, high-frequency surveillance across 140,000+ km of National Highways. We require a camera-mountable, low-cost edge AI system that mounts on ordinary highway patrol vehicles, continuously detects potholes, cracks, lane marking wear, and geometric hazards, and uploads georeferenced road health index data in near real-time even over intermittent 4G/5G connectivity.',
    expectedOutcomes: '1. Automated detection of road distress with >90% precision at speeds up to 80 km/h.\n2. Sub-meter GIS georeferencing of defects integrated with NHAI Data Lake (RAMS).\n3. Reduction in manual inspection cycle time from 6 months to 15 days.\n4. Reduction of survey cost per kilometer by at least 65%.',
    sector: 'Infrastructure & Smart Mobility',
    tags: ['Edge AI', 'Computer Vision', 'NHAI', 'Road Safety', 'GIS Mapping'],
    budgetMin: 3000000,
    budgetMax: 5000000,
    currency: 'INR',
    timelineMonths: 6,
    eligibilityCriteria: '1. DPIIT-recognized startup incorporated in India.\n2. Proven working prototype of computer vision defect detection.\n3. Compliance with MoRTH specifications and CERT-In security norms.\n4. Indian data residency guaranteed on NIC or MeitY empanelled cloud.',
    evaluationCriteria: 'Problem-Solution Fit (20%), Technical Feasibility & Detection Accuracy (15%), Innovation Quotient (15%), Field Scalability (15%), Team Competency (10%), Cost-Effectiveness (10%), Risk & Security (8%), Deployment Readiness (7%).',
    status: 'PILOT_IN_PROGRESS',
    applicationDeadline: '2026-09-30T18:00:00Z',
    publishedAt: '2026-07-15T10:00:00Z',
    totalApplications: 6,
    shortlistedCount: 2,
    winnerCount: 1,
    pilotLocation: 'Delhi-Jaipur Expressway (NH-48) & Eastern Peripheral Expressway (150 km Stretch)',
  },
  {
    id: 'ch-mohfw-02',
    governmentDeptId: 'govt-mohfw',
    ministryName: 'Ministry of Health & Family Welfare',
    departmentName: 'National Health Authority (NHA) & Ayushman Bharat',
    contactPerson: 'Smt. Anita Menon, Joint Secretary (Telemedicine)',
    title: 'Offline-First AI Clinical Triage & Tele-Diagnostics for Sub-Centers',
    slug: 'offline-first-ai-clinical-triage-tele-diagnostics-nha',
    problemStatement: 'Over 150,000 Ayushman Arogya Mandirs (Health & Wellness Centers) in remote rural and tribal regions face severe shortages of specialist doctors. Community Health Officers (CHOs) need an intuitive, multi-lingual digital tool with portable diagnostic peripheral integrations (ECG, Otoscope, Dermascope, Spirometer) that can run offline on Android tablets, generate instant AI clinical risk scores, and route high-risk emergencies to district hospitals via ABDM (Ayushman Bharat Digital Mission) protocols.',
    expectedOutcomes: '1. Multi-lingual voice and text intake in 10+ regional Indian languages.\n2. Integrated ABDM compliant ABHA creation and FHIR electronic health record push.\n3. Instant triage sensitivity >92% for 8 common non-communicable diseases (NCDs).\n4. Fully functional in zero-connectivity environments with store-and-forward sync.',
    sector: 'Healthcare & Life Sciences',
    tags: ['Healthcare', 'Tele-Diagnostics', 'ABDM', 'Ayushman Bharat', 'Offline AI'],
    budgetMin: 3500000,
    budgetMax: 6000000,
    currency: 'INR',
    timelineMonths: 9,
    eligibilityCriteria: '1. DPIIT recognition with biomedical or health-tech focus.\n2. Compliance with CDSCO and ABDM M1/M2/M3 milestone certifications.\n3. Strict adherence to Digital Personal Data Protection (DPDP) Act 2023.',
    evaluationCriteria: 'Diagnostic accuracy, ABDM interoperability, usability by rural ASHA/CHOs, battery efficiency, and patient data encryption standards.',
    status: 'TESTING_IN_PROGRESS',
    applicationDeadline: '2026-09-15T18:00:00Z',
    publishedAt: '2026-07-20T10:00:00Z',
    totalApplications: 5,
    shortlistedCount: 2,
    winnerCount: 0,
    pilotLocation: 'Gadchiroli District (Maharashtra) & Bastar District (Chhattisgarh)',
  },
  {
    id: 'ch-mop-03',
    governmentDeptId: 'govt-power',
    ministryName: 'Ministry of Power',
    departmentName: 'Central Electricity Authority & State DISCOMs',
    contactPerson: 'Er. Sandeep Mukherjee, Director (Distribution Reform)',
    title: 'Non-Intrusive Edge IoT & Waveform Analytics for AT&C Loss Detection',
    slug: 'edge-iot-at-and-c-loss-detection-smart-grid',
    problemStatement: 'Aggregate Technical and Commercial (AT&C) losses exceed 16% in several state power distribution networks due to unregistered taps, bypass tampering, and faulty transformer calibration. DISCOMs require clip-on, non-invasive current/voltage sensors that deploy on Low-Tension (LT) distribution transformers without scheduled shutdowns, analyze high-frequency harmonic waveforms, and isolate the exact feeder branch exhibiting power leakage.',
    expectedOutcomes: '1. Real-time localization of illegal draw or meter bypass within +/- 5 meters on LT feeders.\n2. Zero interruption installation (Hot-line clamp sensor).\n3. Battery life of > 5 years with solar trickle charging.\n4. Reduction in AT&C loss by 3-5 percentage points in target pilot circles.',
    sector: 'Energy & CleanTech',
    tags: ['Smart Grid', 'Power Theft', 'IoT Sensors', 'DISCOM', 'Energy Efficiency'],
    budgetMin: 4000000,
    budgetMax: 7000000,
    currency: 'INR',
    timelineMonths: 6,
    eligibilityCriteria: 'DPIIT startup with certified hardware prototypes compliant with BIS/CEA safety standards.',
    evaluationCriteria: 'Sensor reliability, waveform anomaly detection F1-score, ease of hot-line installation, and DISCOM SCADA integration capability.',
    status: 'SHORTLISTED',
    applicationDeadline: '2026-09-10T18:00:00Z',
    publishedAt: '2026-08-01T10:00:00Z',
    totalApplications: 5,
    shortlistedCount: 2,
    winnerCount: 0,
    pilotLocation: 'Varanasi Smart Distribution Circle (UPPCL)',
  },
  {
    id: 'ch-jal-04',
    governmentDeptId: 'govt-jal',
    ministryName: 'Ministry of Jal Shakti',
    departmentName: 'National Mission for Clean Ganga (NMCG)',
    contactPerson: 'Dr. Vivek Swarup, Scientist-G & NMCG Tech Advisor',
    title: 'Autonomous Solar Water Quality Sentinel Buoys with Pollutant Source Tracing',
    slug: 'autonomous-solar-water-quality-sentinel-buoys-nmcg',
    problemStatement: 'Industrial effluent discharge and agricultural runoff into river basins require dense 24x7 monitoring. Existing static stations are expensive (₹80L+ each) and cannot pinpoint mobile discharge drains. We need self-cleaning, low-cost solar buoys with multi-parameter optical sensors (BOD, COD, DO, Turbidity, pH, Heavy Metals) capable of autonomous drift analysis and source triangulation.',
    expectedOutcomes: '1. Unit cost under ₹3.5 Lakhs per buoy.\n2. Continuous sensor calibration with ultrasonic anti-biofouling wipers.\n3. Automatic SMS/API alerts to Central Pollution Control Board (CPCB) within 3 minutes of threshold breach.\n4. Heatmap dispersion model predicting pollutant plume path 12 hours in advance.',
    sector: 'Water & Environment',
    tags: ['Namami Gange', 'Water Quality', 'IoT Buoy', 'CPCB', 'Clean Water'],
    budgetMin: 2500000,
    budgetMax: 4500000,
    currency: 'INR',
    timelineMonths: 6,
    eligibilityCriteria: 'DPIIT recognized startup with environmental instrumentation credentials.',
    evaluationCriteria: 'Optical sensor accuracy against NABL lab standards, anti-fouling endurance in muddy river flows, telemetry reliability.',
    status: 'APPLICATION_OPEN',
    applicationDeadline: '2026-10-15T18:00:00Z',
    publishedAt: '2026-08-15T10:00:00Z',
    totalApplications: 4,
    shortlistedCount: 0,
    winnerCount: 0,
    pilotLocation: 'Ganga River Basin - Kanpur to Prayagraj Stretch (85 km)',
  },
  {
    id: 'ch-rail-05',
    governmentDeptId: 'govt-railways',
    ministryName: 'Ministry of Railways',
    departmentName: 'Research Designs and Standards Organisation (RDSO)',
    contactPerson: 'Shri Amitabh Saxena, Principal Executive Director (Track)',
    title: 'Acoustic & Vibration AI System for Real-time Railway Track Flaw Detection',
    slug: 'acoustic-vibration-ai-railway-track-flaw-detection-rdso',
    problemStatement: 'To eliminate rail fractures and head-check defects before they cause micro-cracks or derailments, Indian Railways requires locomotive-mounted acoustic sensors and bogie vibration telemetry that scans tracks at operational speeds (up to 130 km/h) and integrates alerts with RDSO Track Management System (TMS).',
    expectedOutcomes: '1. Early detection of internal rail flaw with >94% reliability before visual manifestation.\n2. Operational resilience under extreme vibration and weather (-10°C to +55°C).\n3. Direct wireless transmission to sectional PWI (Permanent Way Inspector) mobile app.',
    sector: 'Railways & Heavy Infrastructure',
    tags: ['Indian Railways', 'RDSO', 'Track Safety', 'Acoustics', 'Vibration AI'],
    budgetMin: 5000000,
    budgetMax: 8000000,
    currency: 'INR',
    timelineMonths: 8,
    eligibilityCriteria: 'DPIIT recognized deep-tech startup with safety instrumentation experience.',
    evaluationCriteria: 'Acoustic signal-to-noise ratio, shock withstand certification (IEC 61373), and algorithm false-positive rate under 2%.',
    status: 'APPLICATION_OPEN',
    applicationDeadline: '2026-10-25T18:00:00Z',
    publishedAt: '2026-08-20T10:00:00Z',
    totalApplications: 3,
    shortlistedCount: 0,
    winnerCount: 0,
    pilotLocation: 'Delhi-Agra High Speed Corridor (Northern Railway)',
  },
];

export const INITIAL_PROPOSALS: Proposal[] = [
  {
    id: 'prop-morth-1',
    challengeId: 'ch-morth-01',
    challengeTitle: 'AI-Powered Automated Pothole & Road Quality Survey on National Highways',
    startupId: 'startup-1',
    startupName: 'MargVision AI Pvt Ltd',
    dpiitNumber: 'DIPP-89421',
    title: 'MargDrishti: Dual-Camera Edge AI Pothole & Roughness Profiler for NHAI Patrols',
    slug: 'margdrishti-edge-ai-pothole-road-profiler',
    solutionOverview: 'MargDrishti is a ruggedized roof-mounted smart camera box powered by NVIDIA Jetson Orin edge computing. It pairs an 8K stereo camera for 3D volumetric pothole depth measurement with a high-accuracy RTK-GNSS receiver and calibrated tri-axial accelerometer. The system runs our custom YOLOv9-Road distress detection model at 60 FPS directly on the patrol vehicle, automatically calculating International Roughness Index (IRI), crack density, and surface hazard indices without requiring post-processing or cloud latency.',
    technicalApproach: '1. Hardware: IP67 rated aluminum enclosure with vibration dampers, dual Sony IMX585 sensors, and Quectel 5G/NavIC module.\n2. Edge AI Pipeline: TensorRT optimized lightweight neural network performing real-time object detection and pixel-level semantic segmentation of 14 road defect classes.\n3. Cloud GIS Portal: Georeferenced defect vectors stream to NHAI RAMS database via secure MQTT with automated priority heatmaps and work-order generation.\n4. Edge Buffering: 512GB NVMe SSD stores raw HD clips with automatic roll-over during zero-connectivity zones.',
    innovation: 'Novel hybrid volumetric depth estimation combining stereo disparity and road surface shadow geometry to calculate pothole asphalt repair volume (cubic meters) instantly in real-time, reducing contractor billing disputes by 100%.',
    teamDetails: 'Core team of 24 engineers led by Dr. Aarav Sharma (PhD AI, IIT Delhi, Ex-Autonomous Driving Scientist) and Priya Nambiar (12+ years GIS & Smart Highway Infrastructure specialist).',
    budgetBreakdown: {
      rdDevelopment: 1200000,
      hardwareInfrastructure: 1400000,
      pilotTesting: 600000,
      teamManpower: 800000,
      contingency: 200000,
    },
    totalBudget: 4200000,
    timelineMonths: 6,
    impactMetrics: 'Enables 100% continuous surveillance of 150 km corridor every 48 hours; reduces survey cost from ₹1,800/km (NSV) to ₹240/km; detects hazardous road craters 12x faster before monsoon aggravation.',
    scalability: 'Modular design can be installed on any vehicle in 15 minutes with standard roof rack clamps. Architecture allows 10,000+ simultaneous vehicles streaming to state NHAI dashboards.',
    riskAnalysis: 'Risk 1: Lens obstruction by dust/rain. Mitigation: Integrated pressurized air-nozzle blower and hydrophobic nano-coating.\nRisk 2: NavIC GPS drift in tunnels. Mitigation: Dead-reckoning IMU wheel odometer fusion.',
    documents: [
      { name: 'MargDrishti_Technical_Architecture_v2.pdf', size: '4.2 MB', url: '#' },
      { name: 'Lab_Benchmark_Report_IIT_Delhi.pdf', size: '2.8 MB', url: '#' },
      { name: 'DPIIT_Verification_Certificate.pdf', size: '1.1 MB', url: '#' },
    ],
    status: 'SHORTLISTED',
    aiScore: 92.4,
    aiScoreBreakdown: {
      problemSolutionFit: 96,
      technicalFeasibility: 94,
      innovation: 93,
      impactPotential: 95,
      teamCapability: 92,
      scalability: 90,
      riskManagement: 88,
      costEffectiveness: 82,
      overall: 92.4,
    },
    aiExplanation: 'Outstanding problem-solution fit for NHAI highway operations. Solution demonstrates exceptional technical feasibility with custom edge stereo vision and robust RTK-GNSS integration. High innovation quotient and experienced IIT-led engineering team. Strongly recommended for G1 Category.',
    g1Category: true,
    g2Category: false,
    rankG1: 1,
    submittedAt: '2026-07-28T14:30:00Z',
    prototypeSubmitted: true,
  },
  {
    id: 'prop-morth-2',
    challengeId: 'ch-morth-01',
    challengeTitle: 'AI-Powered Automated Pothole & Road Quality Survey on National Highways',
    startupId: 'startup-4',
    startupName: 'UrjaSense Smart Grid AI',
    dpiitNumber: 'DIPP-91044',
    title: 'RoadPulse Lite: Smartphone & OBD-II Low-Cost Crowd-Sensed Highway Quality AI',
    slug: 'roadpulse-lite-smartphone-crowdsensed-ai',
    solutionOverview: 'RoadPulse Lite leverages standard commercial smartphones mounted on patrol dashboards combined with an OBD-II CAN-bus dongle to capture vehicle suspension bounce, velocity, and optical footage. A lightweight quantized neural network runs on mobile NPUs to identify road anomalies at fractional hardware costs.',
    technicalApproach: 'On-device Android NPU inference paired with vehicle vertical G-force accelerometer telemetry. Batch synchronizes road distress markers over mobile network to central cloud.',
    innovation: 'Zero proprietary hardware installation required; turns any patrol smartphone into a calibrated road sensor.',
    teamDetails: 'Led by Vikram Mehta (Ex-ISRO embedded systems engineer) and a team of 15 software developers.',
    budgetBreakdown: {
      rdDevelopment: 800000,
      hardwareInfrastructure: 600000,
      pilotTesting: 400000,
      teamManpower: 500000,
      contingency: 100000,
    },
    totalBudget: 2400000,
    timelineMonths: 4,
    impactMetrics: 'Ultra low-cost deployment allowing 50+ patrol vehicles across multiple divisions at budget of only ₹24 Lakhs.',
    scalability: 'Instant software deployment via Play Store / MDM.',
    riskAnalysis: 'Lower optical resolution than dedicated stereo cameras; handled via multi-vehicle crowd-sensed confidence aggregation.',
    documents: [
      { name: 'RoadPulse_Proposal.pdf', size: '3.1 MB', url: '#' },
      { name: 'Cost_Benefit_Model.pdf', size: '1.4 MB', url: '#' },
    ],
    status: 'SHORTLISTED',
    aiScore: 84.8,
    aiScoreBreakdown: {
      problemSolutionFit: 84,
      technicalFeasibility: 86,
      innovation: 80,
      impactPotential: 82,
      teamCapability: 85,
      scalability: 94,
      riskManagement: 80,
      costEffectiveness: 96,
      overall: 84.8,
    },
    aiExplanation: 'Highly economical proposal with exceptional cost-effectiveness score (96/100). Offers rapid scalability at less than 50% of the maximum budget ceiling. Qualifies for G2 Cost-Effective Category.',
    g1Category: false,
    g2Category: true,
    rankG2: 1,
    submittedAt: '2026-07-30T11:15:00Z',
    prototypeSubmitted: true,
  },
  {
    id: 'prop-mohfw-1',
    challengeId: 'ch-mohfw-02',
    challengeTitle: 'Offline-First AI Clinical Triage & Tele-Diagnostics for Sub-Centers',
    startupId: 'startup-2',
    startupName: 'SwasthyaSetu HealthTech',
    dpiitNumber: 'DIPP-72109',
    title: 'ArogyaDrishti: Multi-modal Offline Diagnostic AI Kit for Ayushman Arogya Mandirs',
    slug: 'arogyadrishti-multimodal-diagnostic-ai-kit',
    solutionOverview: 'A compact, battery-powered medical briefcase containing Bluetooth-enabled diagnostic sensors (12-lead ECG, digital stethoscope, pulse-oximeter, and glucometer) paired with an edge AI tablet running on-device multi-lingual triage models in 12 Indian languages.',
    technicalApproach: 'Built using quantized on-device LLMs and CNNs with FHIR M3 integration for ABDM health record exchange. AES-256 local database with peer-to-peer mesh sync to district servers.',
    innovation: 'Voice-interactive clinical assistant in Marathi, Gondi, Hindi and Telugu that guides frontline ASHA workers step-by-step through triage protocols.',
    teamDetails: 'Founders include Dr. Neha Deshmukh (AIIMS Gold Medalist) and S. Kulkarni (Ex-Philips Healthcare Lead Architect).',
    budgetBreakdown: {
      rdDevelopment: 1500000,
      hardwareInfrastructure: 1600000,
      pilotTesting: 800000,
      teamManpower: 900000,
      contingency: 200000,
    },
    totalBudget: 5000000,
    timelineMonths: 9,
    impactMetrics: 'Enables 50,000+ rural patient screenings per year per district with 94% early triage accuracy for cardiovascular and respiratory distress.',
    scalability: 'Standardized kit manufacturable at scale in India under Make in India.',
    riskAnalysis: 'Risk: Device battery in tribal regions without continuous electricity. Mitigation: Integrated 60W portable solar folding panel and 48-hour battery.',
    documents: [
      { name: 'ArogyaDrishti_Clinical_Trial_Data.pdf', size: '5.6 MB', url: '#' },
      { name: 'ABDM_Compliance_Certificate.pdf', size: '1.8 MB', url: '#' },
    ],
    status: 'SHORTLISTED',
    aiScore: 91.2,
    aiScoreBreakdown: {
      problemSolutionFit: 95,
      technicalFeasibility: 92,
      innovation: 92,
      impactPotential: 96,
      teamCapability: 94,
      scalability: 88,
      riskManagement: 86,
      costEffectiveness: 78,
      overall: 91.2,
    },
    aiExplanation: 'Superb clinical and technological alignment with National Health Authority mandates. The multi-lingual voice interface and ABDM FHIR integration provide extraordinary value for rural frontline healthcare. Qualifies as G1 Leader.',
    g1Category: true,
    g2Category: false,
    rankG1: 1,
    submittedAt: '2026-08-04T16:00:00Z',
    prototypeSubmitted: true,
  },
];

export const INITIAL_PROTOTYPES: Prototype[] = [
  {
    id: 'proto-1',
    proposalId: 'prop-morth-1',
    challengeId: 'ch-morth-01',
    startupId: 'startup-1',
    startupName: 'MargVision AI Pvt Ltd',
    solutionTitle: 'MargDrishti: Dual-Camera Edge AI Pothole & Roughness Profiler',
    submissionUrl: 'https://demo.margvision.ai/nhai-portal',
    demoVideoUrl: 'https://youtube.com/watch?v=mock_margvision_nhai',
    repositoryUrl: 'https://github.com/margvision-ai/sangamsetu-nhai-edge-runtime',
    documentation: [
      { title: 'STQC Lab Testing Quickstart Guide', url: '#' },
      { title: 'Hardware Wiring & Calibration Manual', url: '#' },
      { title: 'API Swagger Documentation for NHAI RAMS', url: '#' },
    ],
    architectureNotes: 'Shipped 2 test units to STQC Directorate Laboratory, Electronics City, New Delhi for bench testing and on-vehicle calibration on Delhi-Jaipur highway.',
    submissionDate: '2026-08-10T12:00:00Z',
    status: 'TEST_PASSED',
    testReportId: 'rep-stqc-01',
  },
  {
    id: 'proto-2',
    proposalId: 'prop-mohfw-1',
    challengeId: 'ch-mohfw-02',
    startupId: 'startup-2',
    startupName: 'SwasthyaSetu HealthTech',
    solutionTitle: 'ArogyaDrishti: Multi-modal Offline Diagnostic AI Kit',
    submissionUrl: 'https://portal.swasthyasetu.health/abdm-sandbox',
    demoVideoUrl: 'https://youtube.com/watch?v=mock_swasthyasetu_tribal',
    repositoryUrl: 'https://github.com/swasthyasetu/arogyadrishti-abdm-core',
    documentation: [
      { title: 'CDAC Testing Protocol & Test Harness', url: '#' },
      { title: 'FHIR M3 Data Dictionary', url: '#' },
    ],
    architectureNotes: '5 pre-configured tablets and sensor kits submitted to CDAC Innovation & Testing Center for security, data privacy, and clinical signal validation.',
    submissionDate: '2026-08-14T15:30:00Z',
    status: 'UNDER_TESTING',
    testReportId: 'rep-cdac-02',
  },
];

export const INITIAL_TEST_REPORTS: TestReport[] = [
  {
    id: 'rep-stqc-01',
    prototypeId: 'proto-1',
    proposalId: 'prop-morth-1',
    challengeId: 'ch-morth-01',
    startupName: 'MargVision AI Pvt Ltd',
    solutionTitle: 'MargDrishti: Dual-Camera Edge AI Pothole & Roughness Profiler',
    testingOrgId: 'org-stqc',
    testingOrgName: 'STQC Directorate (Standardisation Testing and Quality Certification), MeitY',
    functionalityScore: 9,
    performanceScore: 10,
    securityScore: 9,
    usabilityScore: 9,
    integrationScore: 9,
    overallScore: 92,
    functionalityReport: 'The dual-camera edge AI system correctly detected 94.6% of verified road surface anomalies during 100 km physical vehicle trials. Volumetric depth accuracy measured within 4.2% of ground truth laser profilers.',
    performanceReport: 'Edge inference latency clocked at 16.4 ms per frame on Jetson Orin (target < 30 ms). Zero dropped frames observed at 85 km/h vehicle speed.',
    securityReport: 'Firmware binary secured with TPM 2.0 hardware root-of-trust. Encrypted MQTT telemetry passed CERT-In level vulnerability assessment without high-severity CVEs.',
    usabilityReport: 'Touch interface on patrol cabin display evaluated by 4 independent highway inspectors; found highly intuitive with audible severity chimes.',
    integrationReport: 'REST/GeoJSON API successfully connected to NHAI RAMS mock endpoints with sub-second synchronization.',
    issues: [
      'Minor lens flare observed during direct sunset angle (mitigated by solar hood attachment)',
      'Recommended adding thermal alert threshold if internal enclosure temperature exceeds 65°C',
    ],
    recommendations: 'Recommended for immediate unconditional approval and scale-out pilot on National Highway stretches. Prototype meets all specifications outlined in tender criteria.',
    verdict: 'PASS',
    certificateNumber: 'STQC/DEL/2026/INNOV-8941',
    submittedAt: '2026-08-22T17:00:00Z',
  },
  {
    id: 'rep-cdac-02',
    prototypeId: 'proto-2',
    proposalId: 'prop-mohfw-1',
    challengeId: 'ch-mohfw-02',
    startupName: 'SwasthyaSetu HealthTech',
    solutionTitle: 'ArogyaDrishti: Multi-modal Offline Diagnostic AI Kit',
    testingOrgId: 'org-cdac',
    testingOrgName: 'Centre for Development of Advanced Computing (C-DAC)',
    functionalityScore: 9,
    performanceScore: 8,
    securityScore: 9,
    usabilityScore: 9,
    integrationScore: 8,
    overallScore: 86,
    functionalityReport: 'Clinical sensor data ingestion tested across 200 synthetic and volunteer patient profiles. ECG waveform interpretation and multi-lingual voice UI demonstrated high diagnostic repeatability.',
    performanceReport: 'Offline inference latency on MediaTek tablet is 1.4 seconds. Battery endurance exceeds 38 continuous hours.',
    securityReport: 'Compliant with DPDP Act 2023. Patient data encrypted with AES-GCM at rest and TLS 1.3 in transit.',
    usabilityReport: 'Frontline workers with minimal IT background completed full patient intake within 3.5 minutes.',
    integrationReport: 'FHIR M2/M3 payloads successfully validated against ABDM Sandbox gateway.',
    issues: [
      'Gondi language voice acoustic model requires minor fine-tuning for high ambient noise clinics.',
    ],
    recommendations: 'Approved with condition to update noise cancellation filter in firmware v1.2 prior to field rollout.',
    verdict: 'CONDITIONAL_PASS',
    certificateNumber: 'CDAC/PUN/2026/HLTH-7210',
    submittedAt: '2026-08-26T14:00:00Z',
  },
];

export const INITIAL_WINNERS: Winner[] = [
  {
    id: 'win-1',
    challengeId: 'ch-morth-01',
    proposalId: 'prop-morth-1',
    startupId: 'startup-1',
    startupName: 'MargVision AI Pvt Ltd',
    solutionTitle: 'MargDrishti: Dual-Camera Edge AI Pothole & Roughness Profiler',
    rank: 1,
    prizeAmount: 4200000,
    selectedAt: '2026-08-25T11:00:00Z',
    notes: 'Selected unanimously by the NHAI Technical Evaluation Board based on top G1 rank (92.4/100) and exemplary STQC Lab Test Verdict (92/100, PASS). Pilot deployment contract issued.',
    contractNumber: 'NHAI/INNOV/2026/SANGAM-001',
  },
];

export const INITIAL_PILOTS: Pilot[] = [
  {
    id: 'pilot-1',
    challengeId: 'ch-morth-01',
    challengeTitle: 'AI-Powered Automated Pothole & Road Quality Survey on National Highways',
    winnerId: 'win-1',
    startupId: 'startup-1',
    startupName: 'MargVision AI Pvt Ltd',
    location: 'Delhi-Jaipur Expressway (NH-48) - 150 km Stretch',
    startDate: '2026-09-01T00:00:00Z',
    endDate: '2027-02-28T00:00:00Z',
    status: 'IN_PROGRESS',
    kpis: [
      { metric: 'Road Survey Frequency', target: 'Every 48 Hours', achieved: 'Every 36 Hours (Exceeding Target)' },
      { metric: 'Pothole Detection Accuracy', target: '>90%', achieved: '94.8% Confirmed by NHAI Field Engineers' },
      { metric: 'RAMS GIS Synchronization', target: '<5 Minutes', achieved: 'Instantaneous (<15s with 5G)' },
      { metric: 'Survey Cost Reduction', target: '>65%', achieved: '74% vs Conventional NSV' },
    ],
    progress: 40,
    currentPhase: 'Phase 2: Live Highway Patrol Integration & RAMS Data Pipeline',
    totalBudget: 4200000,
    disbursedAmount: 1260000,
    milestones: [
      {
        id: 'ms-1',
        pilotId: 'pilot-1',
        title: 'Milestone 1: Hardware Fabrication & STQC Lab Benchmarking',
        description: 'Fabricate 4 roof-mounted MargDrishti camera pods and obtain formal STQC Type Approval Certificate.',
        dueDate: '2026-09-15T00:00:00Z',
        status: 'COMPLETED',
        completedAt: '2026-08-22T00:00:00Z',
        paymentAmount: 1260000,
        paymentStatus: 'PAID',
        paidAt: '2026-08-28T12:00:00Z',
        utrNumber: 'RBI-NEFT-20260828-984129',
        remarks: '30% Mobilization Advance cleared upon STQC Certificate submission.',
      },
      {
        id: 'ms-2',
        pilotId: 'pilot-1',
        title: 'Milestone 2: 150 km Live Corridor Field Trial & RAMS Integration',
        description: 'Continuous 30-day trial on Delhi-Jaipur Expressway with daily automated distress vector pushing to NHAI RAMS.',
        dueDate: '2026-10-31T00:00:00Z',
        status: 'IN_PROGRESS',
        paymentAmount: 1680000,
        paymentStatus: 'REQUESTED',
        remarks: 'Startup has achieved 40% completion; live data telemetry verified by NHAI Regional Office.',
      },
      {
        id: 'ms-3',
        pilotId: 'pilot-1',
        title: 'Milestone 3: Final Performance Audit & Pan-India Scale-up Blueprint',
        description: 'Independent audit report of road maintenance cost savings and delivery of GeM-ready procurement specifications.',
        dueDate: '2027-02-28T00:00:00Z',
        status: 'PENDING',
        paymentAmount: 1260000,
        paymentStatus: 'PENDING',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-startup-1',
    title: 'Milestone 1 Payment Disbursed (₹12,60,000)',
    message: 'Your payment for Milestone 1 of NHAI Pothole AI Pilot has been processed via RBI-NEFT (UTR: RBI-NEFT-20260828-984129).',
    type: 'PAYMENT_RECEIVED',
    read: false,
    createdAt: '2026-08-28T12:30:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-govt-1',
    title: 'STQC Test Report Submitted for MargDrishti',
    message: 'STQC Directorate has uploaded the official test report (Score: 92/100, Verdict: PASS) for MargVision AI proposal.',
    type: 'SUCCESS',
    read: true,
    createdAt: '2026-08-22T17:05:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-test-1',
    title: 'New Prototype Assigned for Testing',
    message: 'ArogyaDrishti by SwasthyaSetu HealthTech has been assigned to CDAC for clinical and ABDM compliance testing.',
    type: 'INFO',
    read: false,
    createdAt: '2026-08-15T09:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'log-1',
    userId: 'user-govt-1',
    userName: 'Dr. Rajesh Verma, IAS (MoRTH)',
    action: 'PILOT_CONTRACT_AWARDED',
    entity: 'Challenge',
    entityId: 'ch-morth-01',
    timestamp: '2026-08-25T11:00:00Z',
    ipAddress: '10.12.44.18 (NIC RailBhavan)',
  },
  {
    id: 'log-2',
    userId: 'user-test-1',
    userName: 'STQC Directorate Lead Evaluator',
    action: 'TEST_REPORT_SUBMITTED',
    entity: 'TestReport',
    entityId: 'rep-stqc-01',
    timestamp: '2026-08-22T17:00:00Z',
    ipAddress: '14.139.58.12 (MeitY STQC)',
  },
  {
    id: 'log-3',
    userId: 'user-admin-1',
    userName: 'DPIIT Mission Director',
    action: 'AI_FAIRNESS_AUDIT_VERIFIED',
    entity: 'AI_Scoring_Model',
    entityId: 'model-v2.4',
    timestamp: '2026-08-20T10:00:00Z',
    ipAddress: '10.20.1.5 (Udyog Bhawan)',
  },
];
